---
title: 07 EXCEPTIONS AND ASSERTIONS
subtitle: 
author: 曲政
date: 2020-05-28
slug: exceptions-and-assertions
tags:
- 
categories:
- mit6000
- ICPP booknotes
typora-root-url: ../../static
show_toc: yes
output: html_notebook
---

### Is "exception" rare?

An “exception” is usually defined as “something that does not conform to the norm,” and is therefore somewhat rare. There is nothing rare about exceptions in Python. They are everywhere. Virtually every module in the standard Python library uses them, and Python itself will raise them in many different circumstances. 

If you know that a line of code might raise an exception when executed, you should handle the exception. In a well-written program, unhandled exceptions should be the exception.

## 7.1 Handling Exceptions

### What is the function that has be generalized to ask for any type of input?

```python
def readVal(valType, requestMsg, errorMsg): 
    while True:
        val = input(requestMsg + ' ')
        try:
            return(valType(val)) #convert str to valType before returning
        except ValueError:
            print(val, errorMsg)
            
readVal(int, 'Enter an integer:', 'is not an integer')
```

## 7.2 Exceptions as a Control Flow Mechanism

### What is the difference in dealing with function with "error" in different programming language? 

In many programming languages, the standard approach to dealing with er- rors is to have functions return a value (often something analogous to Python’s None) indicating that something has gone amiss. Each function invocation has to check whether that value has been returned. In Python, it is more usual to have a function raise an exception when it cannot produce a result that is consistent with the function’s specification.

### What is the `except:` block used for?

In principle, the second except block should never be entered, because the code invoking getRatios should respect the assumptions in the specification of getRatios. However, since checking these assumptions imposes only an insignificant computational burden, it is probably worth practicing defensive programming and checking anyway.

### How is `raise` and `except` used?

```{python}
def getRatios(vect1, vect2):
    """ Assumes: vect1 and vect2 are equal length lists of numbers
        Returns: a list containing the meaningful values of vect1[i]/vect2[i]"""
    ratios = []
    for index in range(len(vect1)):
        try:
            ratios.append(vect1[index]/vect2[index])
        except ZeroDivisionError:
            ratios.append(float('nan')) #nan = Not a Number
        except:
            raise ValueError('getRatios called with bad arguments')
    return ratios
```

```{python}
try:
    print(getRatios([1.0,2.0,7.0,6.0], [1.0,2.0,0.0,3.0]))     
    print(getRatios([], []))
    print(getRatios([1.0, 2.0], [3.0]))
except ValueError as msg: print(msg)
```

```{python}
def getGrades(fname):
    try:
        gradesFile = open(fname, 'r') #open file for reading
    except IOError:
        raise ValueError('getGrades could not open ' + fname)
    grades = []
    for line in gradesFile:
        try:
            grades.append(float(line))
        except:
            raise ValueError('Unable to convert line to float')
    return grades
```

```{python}
try:
    grades = getGrades('quiz1grades.txt')
    grades.sort()
    median = grades[len(grades)//2]
    print('Median grade is', median)
except ValueError as errorMsg:
    print('Whoops.', errorMsg)
```

## 7.3 Assertions

### What are `assert`  statement used for?

Assertions are a useful defensive programming tool. They can be used to confirm that the arguments to a function are of appropriate types. 

They are also a useful debugging tool. The can be used, for example, to confirm that intermediate values have the expected values or that a function returns an acceptable value.
